-- Create template first if it doesn't exist
INSERT INTO anamnesis_templates (id, name, is_active, created_at, updated_at)
SELECT '5c8a49c9-2f5a-4f51-a982-f5e55cd78201', 'Anamnese Micropigmentação', true, now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM anamnesis_templates WHERE name = 'Anamnese Micropigmentação'
);

-- Then update its fields
UPDATE anamnesis_templates
SET fields = '[
  { "id": "4b68bb6e-7009-411a-bd2f-fca21147dbb1", "type": "multiple_choice", "label": "Grávida ou amamentando?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "7dcfa1b7-a384-46c5-95ee-2358bc75c8ee", "type": "multiple_choice", "label": "Esta em periodo Pré Menstrual ou Menstrual?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "bd05a769-cf77-4c42-aa81-422acabed76c", "type": "multiple_choice", "label": "Alérgico?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "d0e1bba8-fc33-4df4-aca1-c1e1948addff", "type": "multiple_choice", "label": "Fumante?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "dbf220f8-c923-455b-bce9-ee347edfa5cb", "type": "multiple_choice", "label": "Faz uso de Produtos para Rejuvenescimento?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "7c13ac47-dd4b-4b13-aec0-0985da010db9", "type": "short_text", "label": "Especifique", "sameLine": true, "isActive": true },
  { "id": "c1f6d900-51b6-4fd4-accc-9954a761e0f0", "type": "short_text", "label": "Se sim, qual produto?", "sameLine": true, "isActive": true },
  { "id": "f516a8fa-7e61-4ed4-9e8c-5727b14d33eb", "type": "multiple_choice", "label": "Já teve reação alérgica a Luvas, Anestesicos, Niquel, Plástico, etc?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "55df4bba-9aa2-45e0-bfea-74caebeaaa5e", "type": "multiple_choice", "label": "Utiliza medicação continua e/ou temporaria?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "06b02660-f65f-4613-8b77-a8a29a6dc74e", "type": "short_text", "label": "Se sim, qual?", "sameLine": true, "isActive": true },
  { "id": "f56b7cd4-40da-4a8e-a22a-fecbfd918349", "type": "multiple_choice", "label": "Esta Aplicando Peelings Quimicos, ou realizando tratamento com laser?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "812b1c41-2c06-4df7-bccd-a34237d6dd64", "type": "multiple_choice", "label": "Possui algum problema de cicatrização?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "dc9c5cc3-f220-41ff-bb37-25e2293ac9e6", "type": "multiple_choice", "label": "Teve alguma ocorrencia com queloides?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "0ae7b173-00f7-418f-a774-6ddc08c90ad7", "type": "multiple_choice", "label": "Sofre Epilepsia ou sofreu nos ultimos 2 anos?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "bc1fc422-b5e0-4a6c-a29d-4731dbfc3fa3", "type": "multiple_choice", "label": "Sofre Hemofilia?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "6a96f130-1c3f-42ae-9bc5-c800882e39db", "type": "multiple_choice", "label": "Sofre de alguma doença Crônica Infecciosa?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "ecbad90f-9f79-450f-a492-de7eb3c563d7", "type": "multiple_choice", "label": "É portador de Hepatite C?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "3beadcb9-5c49-4144-88aa-8d1912f718d7", "type": "multiple_choice", "label": "Tem ou teve Herpes simples ou Zooster?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "e6dd05b3-3aab-49e0-ade2-f1e164f1e9c2", "type": "multiple_choice", "label": "Tem Dermatite Seborreica ou de contato?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "e305e5de-ba11-4770-b7de-846d1bf473c9", "type": "multiple_choice", "label": "É portador de Diabetes?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "ec01c775-5ad2-4cc7-ab32-cbedec642672", "type": "short_text", "label": "Se sim, esta controlada?", "sameLine": true, "isActive": true },
  { "id": "6e8b417c-be82-411a-bf41-7667d4cc06de", "type": "multiple_choice", "label": "Sofre de Pressão Alta ou baixa", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "d0ecaa0f-d477-4ae4-bd2d-411db1bdad59", "type": "multiple_choice", "label": "Sofre Glaucoma?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "b303fe28-6623-40a2-aa90-b3e83b432924", "type": "multiple_choice", "label": "pressão", "options": ["alta", "baixa"], "sameLine": true, "isActive": true },
  { "id": "f5e933e4-6c3f-4279-b1d3-35f111eeb805", "type": "multiple_choice", "label": "Usa lentes de contato?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "4b971a94-47cf-4a41-a3f7-ccb8c25732c5", "type": "multiple_choice", "label": "Esta em Tratamento de Quimioterapia? Se sim, anexar autorização médica", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "1c7b278f-ef54-46ac-bded-63b784ab75de", "type": "multiple_choice", "label": "Esta em pré/pós Tratamento Radioterapia? Se sim anexar autorização médica.", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "58667c46-7c6b-4ac3-a2eb-ed3825501ca1", "type": "multiple_choice", "label": "Sofre de Problemas Circulatórios?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "1e6d9711-b0db-44a6-bcb7-c20ec5cf4dcc", "type": "multiple_choice", "label": "Concorda com a divulgação de imagens de antes e depois do procedimento?", "options": ["Sim", "Não"], "sameLine": false, "isActive": true },
  { "id": "e6741b1d-bb6f-479c-b26a-8b10cb6f43e3", "type": "modelo_padrao", "label": "Contrato Micropigmentação", "content": "Eu, @NomeCliente, portadora de CPF @CPF, endereço @Endereco, concordo que:\n\nA Micropigmentação é o implante de pigmento na pele com a finalidade de simular uma maquiagem permanente no rosto, corrigir ou disfarçar imperfeições, cicatrizes, hipercromias ou discromias. É um procedimento invasivo, que consiste na introdução intradérmica de substâncias corantes por meio de agulhas ou dispositivos que cumpram igual finalidade. A durabilidade do procedimento não dependerá apenas da expertise do profissional, dos produtos e/ou aparelhos utilizados, mas também de outros fatores, desde os cuidados pós-procedimento até os hábitos do cliente.\nCada pele e organismo reage de forma diferente à introdução de um pigmento. A região onde o cliente mora também influenciará na duração, uma vez que a exposição demasiada ao sol e calor ajudarão a desbotar o trabalho antes do tempo esperado, tendo uma durabilidade menor.\n\nQUESTÕES DE CONCORDÂNCIA\n1 - Entendo a importância de fornecer um histórico médico verdadeiro e que qualquer omissão relacionada à minha saúde pode comprometer o resultado do procedimento.\n2 - Não me enquadro na lista de clientes de risco, nem apresento doença infectocontagiosa, sintoma de debilidade imunológica e não estou sob efeito de álcool e/ou drogas.\n3- Estou ciente que alguns medicamentos podem afetar o tratamento, incluindo pequenos sangramentos e inchaços.\n4 - Recebi informações para os cuidados pós procedimento, em folha impressa e meio digital. Estou ciente que sou responsável pelo cuidado pós micropigmentação, e afirmo que seguirei as instruções de cuidados recebidas do profissional.\n5 - Estou de acordo com a simetria e cores de pigmentos que foram selecionadas.\n6 - Entendo que não há como precisar o período de durabilidade do procedimento, devido aos fatores que interferem na fixação do pigmento na pele (Ex: oleosidade, exposição ao sol, sistema imunológico, etc)\n7 - O profissional expos detalhadamente os itens acima e não tenho dúvidas sobre o procedimento. Estou ciente de minhas condições psicológicas e de saúde, isentando o profissional de responsabilidade quanto às reações adversas futuras ou insatisfação, uma vez que foi realizada uma avaliação prévia e nesta me foi apresentado o projeto e possíveis reações adversas.\nIMPORTANTE: Antes do procedimento será feito o registro da área a ser micropigmentada por meio de imagens (fotos)serão registradas fotos antes, projeto, resultado imediato e resultado após cicatrização. Autorizo o uso de minhas imagens para divulgação dos serviços prestados pelo estabelecimento e/ou profissional em congressos, meios virtuais e/ou mídia impressa\n\n@DataAtual", "sameLine": false, "isActive": true },
  { "id": "b05ce5ad-639a-4ae4-90a6-16cb03b6dc24", "type": "modelo_padrao", "label": "Observação Técnicas sobre o procedimento", "content": "Sessão\tTécnica Aplicada\tCor Aplicada\tAgulha\tSensibilidade\n\n\n\n", "sameLine": false, "isActive": true }
]'::jsonb
WHERE name = 'Anamnese Micropigmentação';
